name: LandProtections
main: NurAzliYT\LandProtections\Main
version: 1.0.1
api: 5.0.0
softdepend:
  - BedrockEconomy
commands:
  claim:
    description: "Claim a chunk of land"
    usage: "/claim"
    permission: "landprotections.claim"
  accessland:
    description: "Give access to a chunk of land"
    usage: "/accessland <player_name>"
    permission: "landprotections.accessland"
permissions:
  landprotections.accessland:
    description: "Allows an operator to give access to a chunk of land"
    default: op
  landprotections.claim:
    description: Allows the player to claim a chunk
    default: true
